"""delete memo in flight

Revision ID: 251e7d4de2a6
Revises: 7d493cc8e272
Create Date: 2025-09-26 17:34:24.871624

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "251e7d4de2a6"
down_revision: Union[str, None] = "7d493cc8e272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flight", "memo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flight", sa.Column("memo", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
