"""update accomodation schema

Revision ID: a5c4a1e48d09
Revises: 45bb64c08b68
Create Date: 2025-10-04 00:42:45.799657

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5c4a1e48d09"
down_revision: Union[str, None] = "45bb64c08b68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation", sa.Column("place", sa.String(length=100), nullable=True)
    )
    op.add_column("accommodation", sa.Column("country", sa.String(), nullable=False))
    op.add_column("accommodation", sa.Column("city", sa.String(), nullable=False))
    op.add_column("accommodation", sa.Column("checkin_date", sa.Date(), nullable=False))
    op.add_column(
        "accommodation", sa.Column("checkout_date", sa.Date(), nullable=False)
    )
    op.add_column("accommodation", sa.Column("checkin_time", sa.Time(), nullable=False))
    op.add_column(
        "accommodation", sa.Column("checkout_time", sa.Time(), nullable=False)
    )
    op.add_column("accommodation", sa.Column("description", sa.String(), nullable=True))
    op.drop_column("accommodation", "memo")
    op.drop_column("accommodation", "address")
    op.drop_column("accommodation", "end_date")
    op.drop_column("accommodation", "start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation",
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "accommodation",
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "accommodation",
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "accommodation",
        sa.Column("memo", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("accommodation", "description")
    op.drop_column("accommodation", "checkout_time")
    op.drop_column("accommodation", "checkin_time")
    op.drop_column("accommodation", "checkout_date")
    op.drop_column("accommodation", "checkin_date")
    op.drop_column("accommodation", "city")
    op.drop_column("accommodation", "country")
    op.drop_column("accommodation", "place")
    # ### end Alembic commands ###
