"""add terms

Revision ID: 45bb64c08b68
Revises: 375c12f76c4b
Create Date: 2025-09-29 17:16:34.338967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45bb64c08b68"
down_revision: Union[str, None] = "375c12f76c4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("agreed_terms", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("agreed_privacy", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("agreed_marketing", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "agreed_marketing")
    op.drop_column("user", "agreed_privacy")
    op.drop_column("user", "agreed_terms")
    # ### end Alembic commands ###
