"""itinerary date

Revision ID: f6c19ea32ba2
Revises: a9e50cc05903
Create Date: 2025-07-21 23:42:21.983983

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6c19ea32ba2"
down_revision: Union[str, None] = "a9e50cc05903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("itinerary", sa.Column("itinerary_date", sa.Date(), nullable=False))
    op.drop_column("itinerary", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itinerary", sa.Column("date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("itinerary", "itinerary_date")
    # ### end Alembic commands ###
