"""update flight ticket

Revision ID: b54807b4d316
Revises: 7d493cc8e272
Create Date: 2025-09-24 17:20:58.853596

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b54807b4d316"
down_revision: Union[str, None] = "7d493cc8e272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_segment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("airline", sa.String(), nullable=False),
        sa.Column("flight_number", sa.String(), nullable=False),
        sa.Column("departure_airport", sa.String(), nullable=False),
        sa.Column("arrival_airport", sa.String(), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seat_class", sa.String(), nullable=False),
        sa.Column("seat_number", sa.String(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["flight_id"], ["flight.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_segment_id"), "flight_segment", ["id"], unique=False
    )
    # 1) NULL 위반 방지를 위해 우선 nullable=True + server_default("")로 추가
    op.add_column(
        "flight",
        sa.Column("booking_reference", sa.String(), nullable=True, server_default=""),
    )
    op.add_column(
        "flight",
        sa.Column("passenger_name", sa.String(), nullable=True, server_default=""),
    )

    # 2) 기존 단일편 데이터를 1세그먼트로 백필
    op.execute(
        """
        INSERT INTO flight_segment
            ("order", airline, flight_number, departure_airport, arrival_airport,
             departure_time, arrival_time, seat_class, seat_number, flight_id, is_deleted)
        SELECT 1, airline, flight_number, departure_airport, arrival_airport,
               departure_time, arrival_time, seat_class, seat_number, id, is_deleted
        FROM flight
        """
    )
    op.drop_column("flight", "duration")
    op.drop_column("flight", "seat_number")
    op.drop_column("flight", "memo")
    op.drop_column("flight", "seat_class")
    op.drop_column("flight", "departure_time")
    op.drop_column("flight", "airline")
    op.drop_column("flight", "arrival_airport")
    op.drop_column("flight", "flight_number")
    op.drop_column("flight", "arrival_time")
    op.drop_column("flight", "departure_airport")

    # 3) 기본값 제거 후 NOT NULL로 변경
    op.alter_column("flight", "booking_reference", server_default=None)
    op.alter_column("flight", "passenger_name", server_default=None)
    op.alter_column("flight", "booking_reference", nullable=False)
    op.alter_column("flight", "passenger_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) 우선 nullable=True로 컬럼 복구 (기존 데이터 NULL 허용)
    op.add_column(
        "flight",
        sa.Column(
            "departure_airport", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flight",
        sa.Column(
            "arrival_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flight",
        sa.Column("flight_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("arrival_airport", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("airline", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column(
            "departure_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flight",
        sa.Column("seat_class", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight", sa.Column("memo", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "flight",
        sa.Column("seat_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("duration", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    # 2) flight_segment에서 대표 세그먼트(최소 order)를 가져와 기존 컬럼들 백필
    op.execute(
        """
        UPDATE flight f
        SET
            airline = fs.airline,
            flight_number = fs.flight_number,
            departure_airport = fs.departure_airport,
            arrival_airport = fs.arrival_airport,
            departure_time = fs.departure_time,
            arrival_time = fs.arrival_time,
            seat_class = fs.seat_class,
            seat_number = fs.seat_number
        FROM (
            SELECT DISTINCT ON (flight_id)
                flight_id,
                airline,
                flight_number,
                departure_airport,
                arrival_airport,
                departure_time,
                arrival_time,
                seat_class,
                seat_number
            FROM flight_segment
            ORDER BY flight_id, "order"
        ) fs
        WHERE f.id = fs.flight_id;
        """
    )

    # 2-1) 세그먼트가 없거나 매칭 실패로 남은 NULL 값을 기본값으로 보정
    op.execute(
        """
        UPDATE flight
        SET
            airline = COALESCE(airline, ''),
            flight_number = COALESCE(flight_number, ''),
            departure_airport = COALESCE(departure_airport, ''),
            arrival_airport = COALESCE(arrival_airport, ''),
            seat_class = COALESCE(seat_class, ''),
            seat_number = COALESCE(seat_number, ''),
            departure_time = COALESCE(departure_time, now()),
            arrival_time = COALESCE(arrival_time, now());
        """
    )

    # 3) NOT NULL 제약 복원
    for col in [
        "airline",
        "flight_number",
        "departure_airport",
        "arrival_airport",
        "departure_time",
        "arrival_time",
        "seat_class",
        "seat_number",
    ]:
        op.alter_column("flight", col, nullable=False)

    op.drop_column("flight", "passenger_name")
    op.drop_column("flight", "booking_reference")
    op.drop_index(op.f("ix_flight_segment_id"), table_name="flight_segment")
    op.drop_table("flight_segment")
    # ### end Alembic commands ###