"""add public id

Revision ID: 7a5807e88263
Revises: 74951c647b20
Create Date: 2025-10-26 21:54:10.617089

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a5807e88263"
down_revision: Union[str, None] = "74951c647b20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 nullable=True로 컬럼 추가
    op.add_column("plan", sa.Column("public_id", sa.String(length=36), nullable=True))
    
    # 기존 데이터에 UUID 생성하여 입력
    import uuid
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM plan WHERE public_id IS NULL"))
    plan_ids = [row[0] for row in result]
    
    for plan_id in plan_ids:
        public_id = str(uuid.uuid4())
        connection.execute(
            sa.text("UPDATE plan SET public_id = :public_id WHERE id = :plan_id"),
            {"public_id": public_id, "plan_id": plan_id}
        )
    
    # 이제 nullable=False로 변경
    op.alter_column("plan", "public_id", nullable=False)
    
    # 인덱스 생성
    op.create_index(op.f("ix_plan_public_id"), "plan", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_public_id"), table_name="plan")
    op.drop_column("plan", "public_id")
    # ### end Alembic commands ###
