"""update iti

Revision ID: bb407b7be81b
Revises: a5c4a1e48d09
Create Date: 2025-10-04 16:17:24.824742

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb407b7be81b"
down_revision: Union[str, None] = "a5c4a1e48d09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
