"""decimal amount


Revision ID: b036f531868a
Revises: a37276867783
Create Date: 2025-09-17 17:42:15.766921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b036f531868a"
down_revision: Union[str, None] = "a37276867783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expense",
        "amount",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=20, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expense",
        "amount",
        existing_type=sa.Numeric(precision=20, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
