"""flight req change

Revision ID: 27f082cc6fe0
Revises: 6803ad2218b1
Create Date: 2025-11-25 11:24:30.740793

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27f082cc6fe0"
down_revision: Union[str, None] = "6803ad2218b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flight", "reservation_number", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "flight", "passenger_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "flight_segment", "airline", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "flight_segment", "flight_number", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flight_segment", "flight_number", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "flight_segment", "airline", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "flight", "passenger_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "flight", "reservation_number", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
