"""plan memo add

Revision ID: 7d493cc8e272
Revises: c1d2e3f4abcd
Create Date: 2025-09-22 20:36:33.943488

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d493cc8e272"
down_revision: Union[str, None] = "7d493cc8e271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plan", sa.Column("memo", sa.Text(), nullable=True))
    op.execute("UPDATE plan SET memo = '' WHERE memo IS NULL")
    op.alter_column("plan", "memo", existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "memo")
    # ### end Alembic commands ###
