"""itinerary model fix

Revision ID: a9e50cc05903
Revises: 701e16732a53
Create Date: 2025-07-21 23:36:18.261349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9e50cc05903"
down_revision: Union[str, None] = "701e16732a53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "itinerary", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("itinerary", "location", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("itinerary", "location", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "itinerary", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
