"""iti, accomo del filsu

Revision ID: 456be2c37c94
Revises: 27f082cc6fe0
Create Date: 2025-12-05 17:08:58.661269

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "456be2c37c94"
down_revision: Union[str, None] = "27f082cc6fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accommodation", "country", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("accommodation", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("itinerary", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("itinerary", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("accommodation", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accommodation", "country", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
