"""add segment

Revision ID: b70b1871cd14
Revises: 251e7d4de2a6
Create Date: 2025-09-28 20:11:03.124920

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b70b1871cd14"
down_revision: Union[str, None] = "251e7d4de2a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_segment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("airline", sa.String(), nullable=False),
        sa.Column("flight_number", sa.String(), nullable=False),
        sa.Column("departure_airport", sa.String(), nullable=False),
        sa.Column("arrival_airport", sa.String(), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seat_class", sa.String(), nullable=True),
        sa.Column("seat_number", sa.String(), nullable=True),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["flight_id"], ["flight.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_segment_id"), "flight_segment", ["id"], unique=False
    )
    # 새 컬럼은 기존 데이터가 있어 NotNull 위반을 피하기 위해 우선 nullable + server_default로 추가
    op.add_column(
        "flight",
        sa.Column("reservation_number", sa.String(), nullable=True, server_default=""),
    )
    op.add_column(
        "flight",
        sa.Column("passenger_name", sa.String(), nullable=True, server_default=""),
    )

    # 기존 단일편 컬럼 데이터를 1세그먼트로 백필
    op.execute(
        """
        INSERT INTO flight_segment
            ("order", airline, flight_number, departure_airport, arrival_airport,
             departure_time, arrival_time, seat_class, seat_number, flight_id, is_deleted)
        SELECT 1, airline, flight_number, departure_airport, arrival_airport,
               departure_time, arrival_time, seat_class, seat_number, id, is_deleted
        FROM flight
        """
    )
    op.drop_column("flight", "seat_number")
    op.drop_column("flight", "arrival_time")
    op.drop_column("flight", "seat_class")
    op.drop_column("flight", "airline")
    op.drop_column("flight", "duration")
    op.drop_column("flight", "departure_airport")
    op.drop_column("flight", "flight_number")
    op.drop_column("flight", "arrival_airport")
    op.drop_column("flight", "departure_time")

    # 기본값 제거 후 NOT NULL로 전환
    op.alter_column("flight", "reservation_number", server_default=None)
    op.alter_column("flight", "passenger_name", server_default=None)
    op.alter_column("flight", "reservation_number", nullable=False)
    op.alter_column("flight", "passenger_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 1) 구 컬럼들을 우선 nullable=True로 복구 (기존 데이터 NULL 허용)
    op.add_column(
        "flight",
        sa.Column(
            "departure_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flight",
        sa.Column("arrival_airport", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("flight_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column(
            "departure_airport", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "flight",
        sa.Column("duration", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("airline", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column("seat_class", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "flight",
        sa.Column(
            "arrival_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flight",
        sa.Column("seat_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    # 2) 세그먼트에서 대표 레코드로 백필 (최소 order)
    op.execute(
        """
        UPDATE flight f
        SET
            airline = fs.airline,
            flight_number = fs.flight_number,
            departure_airport = fs.departure_airport,
            arrival_airport = fs.arrival_airport,
            departure_time = fs.departure_time,
            arrival_time = fs.arrival_time,
            seat_class = fs.seat_class,
            seat_number = fs.seat_number
        FROM (
            SELECT DISTINCT ON (flight_id)
                flight_id,
                airline,
                flight_number,
                departure_airport,
                arrival_airport,
                departure_time,
                arrival_time,
                seat_class,
                seat_number
            FROM flight_segment
            ORDER BY flight_id, "order"
        ) fs
        WHERE f.id = fs.flight_id;
        """
    )

    # 2-1) 남은 NULL 안전 보정
    op.execute(
        """
        UPDATE flight
        SET
            airline = COALESCE(airline, ''),
            flight_number = COALESCE(flight_number, ''),
            departure_airport = COALESCE(departure_airport, ''),
            arrival_airport = COALESCE(arrival_airport, ''),
            seat_class = COALESCE(seat_class, ''),
            seat_number = COALESCE(seat_number, ''),
            departure_time = COALESCE(departure_time, now()),
            arrival_time = COALESCE(arrival_time, now());
        """
    )

    # 3) NOT NULL 복원
    for col in [
        "airline",
        "flight_number",
        "departure_airport",
        "arrival_airport",
        "departure_time",
        "arrival_time",
        "seat_class",
        "seat_number",
    ]:
        op.alter_column("flight", col, nullable=False)

    # 4) 신규 컬럼 제거 및 세그먼트 테이블 제거
    op.drop_column("flight", "passenger_name")
    op.drop_column("flight", "reservation_number")
    op.drop_index(op.f("ix_flight_segment_id"), table_name="flight_segment")
    op.drop_table("flight_segment")
    # ### end Alembic commands ###
