"""flight update

Revision ID: 750db88b3f17
Revises: f6c19ea32ba2
Create Date: 2025-07-22 11:08:13.632400

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "750db88b3f17"
down_revision: Union[str, None] = "f6c19ea32ba2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expense", sa.Column("itinerary_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_expense_itinerary_id", "expense", "itinerary", ["itinerary_id"], ["id"]
    )
    op.add_column("flight", sa.Column("duration", sa.String(), nullable=True))
    op.add_column("flight", sa.Column("memo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flight", "memo")
    op.drop_column("flight", "duration")
    op.drop_constraint("fk_expense_itinerary_id", "expense", type_="foreignkey")
    op.drop_column("expense", "itinerary_id")
    # ### end Alembic commands ###
