"""plan title 50

Revision ID: ef44ad8d276f
Revises: 7a5807e88263
Create Date: 2025-11-11 13:21:16.815689

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef44ad8d276f"
down_revision: Union[str, None] = "7a5807e88263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan",
        "title",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan",
        "title",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
