"""flight add fields

Revision ID: 74951c647b20
Revises: 5e8de35745e9
Create Date: 2025-10-22 10:47:54.979999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74951c647b20"
down_revision: Union[str, None] = "5e8de35745e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flight", sa.Column("ticket_number", sa.String(), nullable=True))
    op.add_column("flight", sa.Column("booking_reference", sa.String(), nullable=True))
    op.add_column("flight_segment", sa.Column("gate", sa.String(), nullable=True))
    op.add_column("flight_segment", sa.Column("terminal", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flight_segment", "terminal")
    op.drop_column("flight_segment", "gate")
    op.drop_column("flight", "booking_reference")
    op.drop_column("flight", "ticket_number")
    # ### end Alembic commands ###
