"""empty message

Revision ID: 84b17d34f995
Revises: 6e4e83ba6a55
Create Date: 2026-03-24 10:33:16.668528

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84b17d34f995"
down_revision: Union[str, None] = "6e4e83ba6a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_auth", sa.Column("apple_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "user_auth", ["apple_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_auth", type_="unique")
    op.drop_column("user_auth", "apple_id")
    # ### end Alembic commands ###
