"""add_cities_table

Revision ID: 773af8e3a366
Revises: 6f41601552ab
Create Date: 2026-07-15 11:01:02.296415

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "773af8e3a366"
down_revision: Union[str, None] = "6f41601552ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("city_ascii", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("iso2", sa.String(length=2), nullable=True),
        sa.Column("iso3", sa.String(length=3), nullable=True),
        sa.Column("admin_name", sa.String(length=255), nullable=True),
        sa.Column("capital", sa.String(length=20), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("city_ko", sa.String(length=255), nullable=True),
        sa.Column("country_ko", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cities_city_ascii"), "cities", ["city_ascii"], unique=False
    )
    op.create_index(op.f("ix_cities_city_ko"), "cities", ["city_ko"], unique=False)
    op.create_index(op.f("ix_cities_iso2"), "cities", ["iso2"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cities_iso2"), table_name="cities")
    op.drop_index(op.f("ix_cities_city_ko"), table_name="cities")
    op.drop_index(op.f("ix_cities_city_ascii"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
