"""add_plan_export_table

Revision ID: 6f41601552ab
Revises: 11cae10c2606
Create Date: 2026-06-29 14:33:49.922686

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f41601552ab"
down_revision: Union[str, None] = "11cae10c2606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_export",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("source_plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_export_id"), "plan_export", ["id"], unique=False)
    op.create_index(
        op.f("ix_plan_export_public_id"), "plan_export", ["public_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_export_public_id"), table_name="plan_export")
    op.drop_index(op.f("ix_plan_export_id"), table_name="plan_export")
    op.drop_table("plan_export")
    # ### end Alembic commands ###
