"""remove_place_id_unique_constraint

Revision ID: ba4649c5ce08
Revises: 1ba14228b117
Create Date: 2026-08-31 23:48:55.187850

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba4649c5ce08"
down_revision: Union[str, None] = "1ba14228b117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("location_place_id_key", "location", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("location_place_id_key", "location", ["place_id"])
    # ### end Alembic commands ###
