"""add_location_model_and_fk_to_itinerary_accommodation

Revision ID: 5dee914d1d2c
Revises: 773af8e3a366
Create Date: 2026-08-10 18:41:18.398229

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dee914d1d2c"
down_revision: Union[str, None] = "773af8e3a366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("place_id", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("place_id"),
    )
    op.create_index(op.f("ix_location_id"), "location", ["id"], unique=False)
    op.add_column(
        "accommodation", sa.Column("location_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "accommodation", "location", ["location_id"], ["id"])
    op.drop_column("accommodation", "place")
    op.add_column("itinerary", sa.Column("location_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "itinerary", "location", ["location_id"], ["id"])
    op.drop_column("itinerary", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itinerary",
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("itinerary_location_id_fkey", "itinerary", type_="foreignkey")
    op.drop_column("itinerary", "location_id")
    op.add_column(
        "accommodation",
        sa.Column("place", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "accommodation_location_id_fkey", "accommodation", type_="foreignkey"
    )
    op.drop_column("accommodation", "location_id")
    op.drop_index(op.f("ix_location_id"), table_name="location")
    op.drop_table("location")
    # ### end Alembic commands ###
