"""add_from_google_to_location

Revision ID: ab2f7c8053f7
Revises: def42c5e58e0
Create Date: 2026-08-20 10:48:19.277083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab2f7c8053f7"
down_revision: Union[str, None] = "def42c5e58e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "location",
        sa.Column("from_google", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.alter_column("location", "from_google", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "from_google")
    # ### end Alembic commands ###
