"""add_updated_at_to_location

Revision ID: def42c5e58e0
Revises: 5dee914d1d2c
Create Date: 2026-08-20 10:38:58.847601

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "def42c5e58e0"
down_revision: Union[str, None] = "5dee914d1d2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "updated_at")
    # ### end Alembic commands ###
