"""add_plan_segment

Revision ID: 11cae10c2606
Revises: c5796ce60216
Create Date: 2026-06-26 16:08:44.728412

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11cae10c2606"
down_revision: Union[str, None] = "c5796ce60216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_segment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_segment_plan_id"), "plan_segment", ["plan_id"], unique=False
    )
    # 기존 Plan 데이터를 첫 번째 구간으로 자동 변환
    op.execute("""
        INSERT INTO plan_segment (plan_id, country, city, start_date, end_date, order_index)
        SELECT id, '', '', start_date, end_date, 0
        FROM plan
        WHERE is_deleted = false
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_segment_plan_id"), table_name="plan_segment")
    op.drop_table("plan_segment")
    # ### end Alembic commands ###
