"""add_category_to_itinerary

Revision ID: 5d2733c37924
Revises: ab2f7c8053f7
Create Date: 2026-08-25 16:10:02.536275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d2733c37924"
down_revision: Union[str, None] = "ab2f7c8053f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itinerary", sa.Column("category", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("itinerary", "category")
    # ### end Alembic commands ###
