"""add_area_cd_signgu_cd_to_location

Revision ID: 1ba14228b117
Revises: 5d2733c37924
Create Date: 2026-08-31 21:45:03.774378

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ba14228b117"
down_revision: Union[str, None] = "5d2733c37924"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location", sa.Column("area_cd", sa.String(), nullable=True))
    op.add_column("location", sa.Column("signgu_cd", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "signgu_cd")
    op.drop_column("location", "area_cd")
    # ### end Alembic commands ###
